### ISSUE TITLE
最新版群晖启动失败

### ISSUE THREAD

**Issue by chenlu964** [ztc1997/ikuai-bypass#7]
配置没动，更新了镜像就启动不了了
报错如下：
failed to create shim task: 0Cl runtime create failed: runc create failed: unable to start
container process: exec:"./ikuai-bypass": permission denied: unknown

**Comment by chenlu964** [comment]
![Uploading 77.png…]()

**Comment by chenlu964** [comment]
![77](https://github.com/ztc1997/ikuai-bypass/assets/86452332/f16b5316-8a46-4574-8607-a92fef2f9090)

**Comment by Delyfeel** [comment]
同样，ikuaidocker和unraid都无法运行最新版1.4

**Comment by ZoftTy** [comment]
手动添加 **ikuai-bypass** 的权限

```shell
chmod +x /build/ikuai-bypass
```

compose 如下：

```yaml
services:
  ikuai-bypass:
    image: ztc1997/ikuai-bypass:latest
    container_name: ikuai-bypass
    command: "sh -c 'chmod +x ./ikuai-bypass && ./ikuai-bypass -c /etc/ikuai-bypass/config.yml'"
    volumes:
      - "/stacks/ikuai-bypass:/etc/ikuai-bypass"
```
